name: Publish website

on:
  schedule:
    - cron:  '0 0 * * *' # run nightly

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm install yarn@latest
    - run: yarn install
    - run: yarn download
    - run: yarn dl2json

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs # The folder the action should deploy.